baseURL: https://theorangeone.net
languageCode: en-gb
title: TheOrangeOne

params:
  author: TheOrangeOne
  author_name: Jake Howard
  summary_length: 125
  summary_length_long: 200
  nav_items: 5
  index_items: 6

outputFormats:
  markdown:
    name: "txt"
    mediaType: "text/plain"
    isPlainText: true
outputs:
  home:
    - "html"
    - "rss"
  section:
    - "html"
    - "rss"
    - "txt"
  page:
    - "html"
    - "txt"
    - "json"

staticDir: "static/build"

buildDrafts: false
buildFuture: true
buildExpired: true

enableGitInfo: false
enableRobotsTXT: true
rssLimit: 100

disableHugoGeneratorInject: true
enableEmoji: true
MetaDataFormat: yaml
disableKinds:
  - taxonomy
  - taxonomyTerm

pygmentsCodeFencesGuessSyntax: true
PygmentsCodeFences: true
pygmentsuseclasses: true
