baseURL: https://theorangeone.net
languageCode: en-gb
title: TheOrangeOne

params:
  author: TheOrangeOne
  author_name: Jake Howard
  summary_length: 100

staticDir: "static/build"

buildDrafts: false
buildFuture: true
buildExpired: true

enableGitInfo: false
enableRobotsTXT: true

disableHugoGeneratorInject: true
enableEmoji: true

pygmentsCodeFencesGuessSyntax: true
rssLimit: 100

blackfriday:
  hrefTargetBlank: true
