baseURL: https://theorangeone.net
languageCode: en-gb
title: TheOrangeOne

params:
  author: TheOrangeOne
  author_name: Jake Howard
  nav_items: 5
  index_items: 6
  iso8601: "2006-01-02T15:04:05"

summaryLength: 40

outputFormats:
  markdown:
    name: "txt"
    mediaType: "text/plain"
    isPlainText: true
outputs:
  home:
    - "html"
    - "rss"
    - "json"
  section:
    - "html"
    - "rss"
    - "txt"
  page:
    - "html"
    - "txt"
    - "json"

staticDir: "static/build"

buildDrafts: false
buildFuture: true
buildExpired: true

enableGitInfo: false
enableRobotsTXT: true
rssLimit: 100

disableHugoGeneratorInject: true
enableEmoji: true
MetaDataFormat: yaml

pygmentsCodefencesGuessSyntax: true
pygmentsCodefences: true
pygmentsUseClasses: true
