baseURL: https://theorangeone.net
languageCode: en-gb
title: TheOrangeOne

timeout: 20000

params:
  author: TheOrangeOne
  author_name: Jake Howard
  nav_items: 5
  index_items: 6
  iso8601: "2006-01-02T15:04:05"

summaryLength: 40

staticDir: "static/build"

buildFuture: true

enableRobotsTXT: true
rssLimit: 10000

disableHugoGeneratorInject: true
enableEmoji: true
MetaDataFormat: yaml
stepAnalysis: true

pygmentsCodefencesGuessSyntax: true
pygmentsCodefences: true
pygmentsUseClasses: true

imaging:
  resampleFilter: Lanczos

markup:
  goldmark:
    renderer:
      unsafe: true
theme:
  - utils

assetDir: static/build/

related:
  threshold: 1
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 1
    - name: keywords
      weight: 1
    - name: title
      weight: 1
    - name: subtitle
      weight: 1
