version: "2.3"

services:
  website:
    build:
      context: .
    env_file: .env
    volumes:
      - "./public:/usr/share/nginx/html:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
