version: 2.0

jobs:
    build:
        docker:
            - image: circleci/node:8.10
        environment:
            - npm_config_loglevel: notice
        steps:
            - checkout
            - run:
                name: Install Hugo
                command: wget https://github.com/gohugoio/hugo/releases/download/v0.40.3/hugo_0.40.3_Linux-64bit.deb -O /tmp/hugo.deb && sudo dpkg -i /tmp/hugo.deb
            - restore_cache:
                key: npm-{{ checksum "package-lock.json" }}
            - run:
                name: Install dependencies
                command: npm install
            - save_cache:
                key: npm-{{ checksum "package-lock.json" }}
                paths:
                - node_modules
            - run:
                name: Build site
                command: ./scripts/release.sh
            - run:
                name: Run Tests
                command: ./scripts/test.sh
