name: Deploy

on:
  push:
    branches:
      - master


env:
  FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
  FLICKR_USER_ID: ${{ secrets.FLICKR_USER_ID }}
  UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          extended: true

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/cache@v1
        with:
          path: $HOME/.npm
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Build site
        run: ./scripts/release.sh

      - name: rclone
        uses: wei/rclone@master
        with:
          args: sync -v public/ pages:theorangeone.net/
        env:
          RCLONE_CONFIG_PAGES_TYPE: webdav
          RCLONE_CONFIG_PAGES_URL: https://pages.theorangeone.net
          RCLONE_CONFIG_PAGES_USER: github
          RCLONE_CONFIG_PAGES_PASS: ${{ secrets.RCLONE_WEBDAV_PASSWORD }}
