name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Build production container
        run: docker build --tag docker.pkg.github.com/${GITHUB_REPOSITORY,,}/prod:latest .

      - name: Log into GitHub Docker Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY%/*} --password-stdin

      - name: Push the Docker container
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY,,}/prod:latest
